Add pyflakes
Adds the linter pyflakes to the system, to aid in catching code smells

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -6,8 +6,15 @@ if [ ! -x "${black_path}" ]; then
   exit 1
 fi
 
+pyflakes_path=$(command -v pyflakes)
+if [ ! -x "${pyflakes_path}" ]; then
+  echo "ERROR: 'pyflakes' tool is not found in path. Please ensure it's installed."
+  exit 1
+fi
+
 changed_python_files=$(git diff --cached --name-only --diff-filter=ACM | egrep '^.+\.py$')
 if ! [ -z "${changed_python_files}" ]; then
+  pyflakes $changed_python_files || (echo "ERROR: 'pyflakes' found issues, aborting commit" && exit 1)
   black $changed_python_files
   git add $changed_python_files
 fi
